export const integrantes = [
    { id: 0, name: 'Amanda', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055466162269466634/Amanda.jpg', descricao: 'Oi! Meu nome é Amanda, tenho 18 anos e sou uma desenvolvedora web fullstack júnior. A tecnologia me encanta por ser uma área em constante expansão e por conseguir ver ela em tudo em nossa volta. Tenho conhecimento em JavaScript, TypeScript, NestJs, HTML, CSS, React e MySQL. Durante a realização desse projeto, pude desenvolver também minhas habilidades comportamentais como colaboração, comunicação e detalhes que contribuiram para a realização da rede social.', linkedin: 'https://www.linkedin.com/in/amanda-rocha-a51767253/', github: 'https://github.com/seugirdorx' },
    { id: 1, name: 'Ana', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055476941672681542/IMG_20211031_002242_342.png', descricao: 'Me chamo Ana Clara Azevedo, tenho 22 anos e sou Desenvolvedora Full Stack Júnior. Formada pelo Bootcamp da Generation, em parceiria com a Prefeitura do Rio de Janeiro. Utilizando tecnologias e linguagens diferentes (como JavaScript, TypeScrip, React, HTML, CSS, entre outros... ) para desenvolver aplicações web.', linkedin: 'https://www.linkedin.com/in/ana-clara-azevedo-fullstackdev/', github: 'https://github.com/AnaClaraazz' },
    { id: 2, name: 'Daniel', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055456453902733342/1652729663081.jpg', descricao: 'Me chamo Daniel sou um desenvolvedor full stack junior formado em um bootcamp da generation Brasil, onde aprendi conceitos essencias para o mercado de programação como Bsms que agregavam na minhas soft skills e habilidades de programação front end como HTML, CSS, Javascript, Rectjs, Nextjs, Typescript. E no back end com Mysql, nestjs. E versonamento de codigos com git e github.', github: 'https://github.com/DanielSanCo' },
    { id: 3, name: 'Gabriel', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055456515349303347/IMG_20221220_111117.jpg', descricao: 'Olá, meu nome é Gabriel Mario, sou estudante do 4º período de Engenharia Civil, tenho 25 anos, sou um desenvolvedor Web FullStack Jr formado pela Generation Brasil, estou em uma mudança de carreira, do setor de atendimento ao cliente, para a área de tecnologia. Na formação, pude desenvolver conhecimentos em backend, com as tecnologias: JS, NestJs, TypeScript, MySql, e também, no frontend, com o HTML, CSS, React.', linkedin: 'https://www.linkedin.com/in/gabriel-mario-jesus-de-oliveira-778880250/', github: 'https://github.com/jesusgm0' },
    { id: 4, name: 'Iury', img: 'https://media.discordapp.net/attachments/1014218248998367252/1055501978681229370/IMG-20221222-WA0006.jpg?width=662&height=663', descricao: 'Oi pessoal, bom dia. Meu nome é Iury, tenho 26 anos e atuei principalmente na parte do front-end da aplicação onde eu pude colocar meus conhecimentos em diversas técnologias em prática. Atualmente estou buscando aperfeiçoamento no React e em tecnologias voltadas para a construção da interface do usuario para me aprimorar cada dia mais como um desenvolvedor front-end.', linkedin: 'https://www.linkedin.com/in/iury-freitas-382018227/', github: 'https://github.com/Iury96' },
    { id: 5, name: 'Layon', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055456796816441354/FB_IMG_1671710875807.jpg', descricao: 'Sou Layon, tenho 22 anos e bastante dedicado. Estou constantemente buscando me desenvolver, tanto em habilidades técnicas, quanto comportamentais que, aliás, tenho como destaque o trabalho em equipe e a comunicação bem interativa. Atualmente sou formado em JavaScript, como Desenvolvedor Júnior Full Stack e tenho conhecimentos em Nest.Js, Node.js, JavaScript/TypeScript, Bycript, JWT, API, CSS, HTML, React, Bootstrap, Material ui, Git/GitHub e MySQL.', linkedin: 'https://www.linkedin.com/in/layon-silva-6a38231b1/', github: 'https://github.com/layonss' },
    {
        id: 6, name: 'Romulo', img: 'https://cdn.discordapp.com/attachments/1022847836406165519/1055460355666612305/20221222_091305.jpg', descricao: 'Olá pessoal, bom dia. Meu nome é Romulo, tenho 28 anos e sou desenvolvedor FullStack. Atualmente atuo mais na parte do front-end onde venho procurando aprimorar as minhas habilidades e adquirir novos conhecimentos para poder continuar o meu crescimento profissional, buscando sempre novos desafios e me dedicando ao máximo para poder colaborar com os meus colegas de equipe.', linkedin: '', github: 'https://github.com/romuloks'  },
]